name: Build and deploy Node.js app to Azure Web App - sitename

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#     env:
#       working-directory: ./frontend

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: yarn install, build
        run: |
          cd ./frontend
          yarn install
          yarn run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app-front
          path: build/front/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-front

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apt-front'
          slot-name: 'Production'
          publish-profile:
            ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B8354A470E6425193A599C8E5D66100 }}
          package: .
